export const characterNameFilterRecord: Record<CharacterName, boolean> = {
    "鳳ここな": true,
    "静香": true,
    "カトリナ・グリーベル": true,
    "新妻八恵": true,
    "柳場ぱんだ": true,
    "流石知冴": true,
    "連尺野初魅": true,
    "烏森大黒": true,
    "舎人仁花子": true,
    "萬容": true,
    "筆島しぐれ": true,
    "千寿暦": true,
    "ラモーナ・ウォルフ": true,
    "王雪": true,
    "リリヤ・クルトベイ": true,
    "与那国緋花里": true,
    "千寿いろは": true,
    "白丸美兎": true,
    "阿岐留カミラ": true,
    "猫足蕾": true,
    "本巣叶羽": true,
}

export const allCharacterNames: CharacterName[] = [
    "鳳ここな",
    "静香",
    "カトリナ・グリーベル",
    "新妻八恵",
    "柳場ぱんだ",
    "流石知冴",
    "連尺野初魅",
    "烏森大黒",
    "舎人仁花子",
    "萬容",
    "筆島しぐれ",
    "千寿暦",
    "ラモーナ・ウォルフ",
    "王雪",
    "リリヤ・クルトベイ",
    "与那国緋花里",
    "千寿いろは",
    "白丸美兎",
    "阿岐留カミラ",
    "猫足蕾",
    "本巣叶羽",
]